#!/usr/bin/env python3
"""
dxcc_monitor.py — Real-time DXCC monitor via Telnet DX Cluster
Compares cluster spots against your ADIF log and sends Telegram alerts for new entities.

Usage:
    python3 dxcc_monitor.py --callsign YOURCALL --telegram-token TOKEN --telegram-chat-id CHAT_ID
    python3 dxcc_monitor.py --callsign YOURCALL --modes SSB,FT8 --years 2026
"""

import socket
import re
import json
import time
import os
import argparse
import requests
import threading
import subprocess
import adif_io
from datetime import datetime

# ===================== CONFIGURATION =====================
WORKSPACE = os.path.dirname(os.path.abspath(__file__))

# ===================== ARGPARSE =====================
def parse_args():
    parser = argparse.ArgumentParser(
        description="Real-time DXCC monitor via Telnet DX Cluster",
        epilog="""Example: python3 dxcc_monitor.py --callsign YOURCALL \\
  --telegram-token 123456:ABC --telegram-chat-id 987654 \\
  --modes SSB,FT8 --year 2026"""
    )
    current_yr = str(datetime.now().year)
    # Filters
    parser.add_argument("--year", "-y", default=current_yr,
                        help=f"Year to filter (default: {current_yr})")
    parser.add_argument("--modes", "-m", default="SSB",
                        help="Comma-separated modes (default: SSB). FT8 is special: only alerts for never-worked countries unless included here.")
    parser.add_argument("--freq-min", type=float, default=3000,
                        help="Min frequency in kHz (default: 3000 ~80m)")
    parser.add_argument("--freq-max", type=float, default=55000,
                        help="Max frequency in kHz (default: 55000 ~6m)")
    # Connections
    parser.add_argument("--telegram-token", default=None,
                        help="Telegram Bot API token")
    parser.add_argument("--telegram-chat-id", default=None,
                        help="Telegram chat ID to send alerts to")
    parser.add_argument("--cluster-host", default="dxc.pi4cc.nl",
                        help="DX Cluster host (default: dxc.pi4cc.nl)")
    parser.add_argument("--cluster-port", type=int, default=8000,
                        help="DX Cluster port (default: 8000)")
    parser.add_argument("--callsign", required=True,
                        help="Your callsign (used to connect to the cluster)")
    parser.add_argument("--eqsl-user", default=None,
                        help="eQSL username (for ADIF download)")
    parser.add_argument("--eqsl-pass", default=None,
                        help="eQSL password (for ADIF download)")
    args = parser.parse_args()

    # Validate
    if args.telegram_token and not args.telegram_chat_id:
        parser.error("--telegram-chat-id is required when --telegram-token is set")

    return args

# Globals (set from argparse in main)
ARGS = None

# ADIF file
ADIF_FILE = os.path.join(WORKSPACE, "logbook.adi")

# Prefix map files (generated by parse_cty.py)
PREFIX_FILE = os.path.join(WORKSPACE, "dxcc_prefixes.json")
CTY_FILE = os.path.join(WORKSPACE, "cty.dat")


# ===================== QUIET HOURS =====================

def is_quiet_hours():
    """Returns True during quiet hours (23:30 - 07:30 local time)."""
    now = datetime.now()
    current = now.hour * 60 + now.minute
    start = 23 * 60 + 30  # 23:30
    end = 7 * 60 + 30     # 07:30
    if start <= current or current < end:
        return True
    return False

# ===================== INIT =====================

# Spot regex: "DX de SPOTTER: FREQ DX_CALL COMMENT"
SPOT_RE = re.compile(r"^DX\s+de\s+(\S+):\s+([0-9.]+)\s+([A-Z0-9/]+)(.*)", re.IGNORECASE)

# Worked set: (year, mode, entity)
dxcc_worked = set()
last_alert_time = {}  # (year, mode, entity) -> timestamp
last_freq = {}        # (year, mode, entity) -> freq_khz
REALERT_HOURS = 2

# Prefix map (loaded from JSON)
dxcc_prefixes = {}       # prefix_str -> entity_name
sorted_prefixes = []     # sorted by descending length
dxcc_exact = {}          # exact callsign -> entity_name (cty.dat exceptions)
dxcc_excludes = {}       # callsign -> prefix_to_skip
dxcc_entities = []       # curated DXCC entity list
region_map = {}          # sub-region -> parent entity


def load_prefix_map():
    global dxcc_prefixes, sorted_prefixes, dxcc_exact, dxcc_excludes
    if os.path.exists(PREFIX_FILE):
        with open(PREFIX_FILE) as f:
            data = json.load(f)
        dxcc_prefixes = data["map"]
        sorted_prefixes = data["prefixes"]
        dxcc_exact = data.get("exact", {})
        dxcc_excludes = data.get("excludes", {})
        dxcc_entities[:] = data.get("dxcc_entities", [])
        region_map.clear()
        region_map.update(data.get("region_map", {}))
        raw_count = len(set(dxcc_prefixes.values()))
        ent_count = len(dxcc_entities) if dxcc_entities else raw_count
        print(f"Prefix map loaded: {len(dxcc_prefixes)} prefixes, {len(dxcc_exact)} exceptions, "
              f"{len(dxcc_excludes)} excludes, {ent_count} entities")
        return
    print("dxcc_prefixes.json not found. Run parse_cty.py first.")
    exit(1)


def lookup_entity(callsign):
    """Longest-prefix match with cty.dat exceptions.
    Portable suffix support: KH7AL/KH9 -> KH9 -> Wake Island.
    """
    raw = callsign.upper()
    cs = raw.replace("/", " ")
    base_call = cs.split()[0]

    # KG4: 1 or 3 letter suffix = United States
    kg4_match = re.match(r'^KG4([A-Z]{1,3})$', base_call)
    if kg4_match:
        suffix_len = len(kg4_match.group(1))
        if suffix_len != 2 and suffix_len != 0:
            return "United States"

    # Exact match (cty.dat exceptions)
    if raw in dxcc_exact:
        return dxcc_exact[raw]
    if base_call in dxcc_exact:
        return dxcc_exact[base_call]

    # Portable suffix as prefix
    if '/' in raw:
        suffix = raw.split('/')[-1]
        if suffix in dxcc_prefixes:
            return dxcc_prefixes[suffix]
        best_len = 0
        best = None
        for p in sorted_prefixes:
            if suffix.startswith(p) and len(p) > best_len:
                best_len = len(p)
                best = dxcc_prefixes[p]
        if best:
            return best
        # Try base/suffix (e.g. SV/a -> Mount Athos)
        base_prefix = ""
        for p in sorted_prefixes:
            if base_call.startswith(p):
                base_prefix = p
                break
        if base_prefix:
            portable_candidate = f"{base_prefix}/{suffix}"
            if portable_candidate in dxcc_prefixes:
                return dxcc_prefixes[portable_candidate]
            for p in sorted_prefixes:
                if portable_candidate.startswith(p) and len(p) > len(base_prefix):
                    return dxcc_prefixes[p]

    # Standard prefix match (skipping excludes)
    best_len = 0
    best = "UNKNOWN"
    for p in sorted_prefixes:
        if cs.startswith(p) and len(p) > best_len:
            if dxcc_excludes.get(base_call) == p:
                continue
            best_len = len(p)
            best = dxcc_prefixes[p]
    return best


# ===================== ADIF / eQSL =====================

def download_adif():
    """Downloads full ADIF log from eQSL (OutBox)."""
    import html.parser

    class LinkExtractor(html.parser.HTMLParser):
        def __init__(self):
            super().__init__()
            self.adif_url = None
        def handle_starttag(self, tag, attrs):
            if tag == "a":
                attrs_dict = dict(attrs)
                href = attrs_dict.get("href", "")
                if href.endswith(".adi"):
                    self.adif_url = href

    url_api = f"https://www.eqsl.cc/qslcard/DownloadADIF.cfm?UserName={ARGS.eqsl_user}&Password={ARGS.eqsl_pass}&HamOnly=1"
    try:
        r = requests.get(url_api, timeout=60)
        r.raise_for_status()
        parser = LinkExtractor()
        parser.feed(r.text)
        if not parser.adif_url:
            print("No ADIF link found in eQSL response")
            return False
        if parser.adif_url.startswith("../"):
            parser.adif_url = "https://www.eqsl.cc/" + parser.adif_url[3:]
        print(f"ADIF link: {parser.adif_url}")
    except Exception as e:
        print(f"Error getting ADIF link: {e}")
        return False

    try:
        r2 = requests.get(parser.adif_url, timeout=60)
        r2.raise_for_status()
        clean = r2.content.decode("utf-8", errors="replace").encode("utf-8", errors="replace")
        with open(ADIF_FILE, "wb") as f:
            f.write(clean)
        print(f"ADIF downloaded ({len(clean)} bytes)")
        return True
    except Exception as e:
        print(f"Error downloading ADIF: {e}")
        return False


def load_adif():
    """Loads ADIF file and populates dxcc_worked."""
    global dxcc_worked
    if not os.path.exists(ADIF_FILE):
        print(f"ADIF not found: {ADIF_FILE}")
        return 0
    try:
        with open(ADIF_FILE, "rb") as f:
            raw = f.read()
        text = raw.decode("utf-8", errors="replace")
        qsos, _ = adif_io.read_from_string(text)
        dxcc_worked.clear()
        for qso in qsos:
            date = qso.get("QSO_DATE", "")
            year = date[:4] if len(date) >= 4 else ""
            mode = qso.get("MODE", "").upper()
            call = qso.get("CALL", "").upper()
            if year and mode and call:
                entity = lookup_entity(call)
                dxcc_worked.add((year, mode, entity))
        print(f"ADIF loaded: {len(qsos)} QSOs, {len(dxcc_worked)} (year/mode/entity) combos")
        return len(qsos)
    except Exception as e:
        print(f"Error loading ADIF: {e}")
        return 0


def refresh_adif():
    """Refresh ADIF and return True on success."""
    ok = download_adif()
    if ok:
        load_adif()
    return ok


# ===================== MODE GUESSING =====================

def guess_mode(freq_khz, comment):
    """Guess mode from comment text, fallback to frequency band."""
    c = comment.upper()
    if "FT8" in c: return "FT8"
    if "FT4" in c: return "FT4"
    if "CW" in c: return "CW"
    if "SSB" in c: return "SSB"
    if "RTTY" in c: return "RTTY"
    # Frequency-based fallback
    if 14000 <= freq_khz <= 14070: return "CW"
    if 21000 <= freq_khz <= 21070: return "CW"
    if 7000 <= freq_khz <= 7040: return "CW"
    if (7074 <= freq_khz <= 7076) or (14074 <= freq_khz <= 14076): return "FT8"
    if 14100 <= freq_khz <= 14350: return "SSB"
    return "UNKNOWN"


# ===================== TELEGRAM =====================

def send_telegram(msg):
    """Send a message via Telegram Bot API."""
    if not ARGS.telegram_token or not ARGS.telegram_chat_id:
        print(f"[Telegram would send] {msg}")
        return
    try:
        requests.post(
            f"https://api.telegram.org/bot{ARGS.telegram_token}/sendMessage",
            json={"chat_id": ARGS.telegram_chat_id, "text": msg, "parse_mode": "Markdown"},
            timeout=5
        )
    except Exception as e:
        print(f"Telegram error: {e}")


# ===================== NEVER WORKED ENTITIES =====================

entities_never_worked = set()


def rebuild_never_worked():
    """Rebuild the set of DXCC entities never worked (any year, any mode).
    Uses the curated dxcc_entities list (340 ARRL entities).
    Sub-regions kept separate (340 entities mode).
    """
    global entities_never_worked
    worked_names = set()
    for (year, mode, entity) in dxcc_worked:
        worked_names.add(entity)
    known = set(dxcc_entities) if dxcc_entities else set()
    entities_never_worked.clear()
    for e in known:
        if e not in worked_names:
            entities_never_worked.add(e)
    print(f"Never-worked entities: {len(entities_never_worked)}/{len(known)}")


# ===================== SPOT PROCESSING =====================

def process_spot(line):
    match = SPOT_RE.search(line)
    if not match:
        return
    spotter = match.group(1).upper()
    freq = float(match.group(2))
    dx_call = match.group(3).upper()
    comment = match.group(4)

    mode = guess_mode(freq, comment)

    # CW always ignored
    if mode == "CW":
        return

    # Frequency range filter
    if freq < ARGS.freq_min or freq > ARGS.freq_max:
        return

    entity = lookup_entity(dx_call)
    current_year = ARGS.year
    is_brand_new = entity in entities_never_worked

    # FT8: only alert for never-worked countries (unless included in --modes)
    if mode == "FT8":
        if not is_brand_new:
            return
    elif mode not in set(m.strip() for m in ARGS.modes.split(",")):
        return

    key = (current_year, mode, entity)

    # Already worked in log
    if key in dxcc_worked:
        return

    now = time.time()
    last = last_alert_time.get(key, 0)
    hours_since = (now - last) / 3600
    is_never_alerted = last == 0
    should_alert = False
    is_freq_change = False
    is_reavert = False

    if is_never_alerted:
        should_alert = True
    else:
        old_freq = last_freq.get(key, 0)
        is_freq_change = abs(freq - old_freq) > 0.1  # QSY detected
        is_reavert = hours_since >= REALERT_HOURS    # >2h since last alert
        if is_freq_change or is_reavert:
            should_alert = True

    if should_alert:
        last_alert_time[key] = now
        last_freq[key] = freq

        re_text = ""
        if is_reavert:
            re_text = f" (re-alerted after {hours_since:.1f}h)"
        if is_freq_change:
            re_text = f" (QSY! was {old_freq} kHz)"

        brand_new_text = ""
        if is_brand_new:
            brand_new_text = "\n🌍 *NEW ONE !!!*"

        msg = (
            f"Filter {current_year}{re_text}\n\n"
            f"📡 {dx_call} → {entity}\n"
            f"📻 {freq} kHz | {mode}"
        )
        msg_tg = msg + brand_new_text + f"\n📢 {spotter}"
        print(msg + brand_new_text.replace("*", "") + f"\n📢 {spotter}")

        # Always send for brand-new countries; respect quiet hours otherwise
        if is_brand_new or not is_quiet_hours():
            send_telegram(msg_tg)


# ===================== TELNET CLIENT =====================

def cluster_loop():
    """Maintains a persistent Telnet connection to the DX Cluster."""
    while True:
        try:
            print(f"Connecting to {ARGS.cluster_host}:{ARGS.cluster_port}...")
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.settimeout(120)
                s.connect((ARGS.cluster_host, ARGS.cluster_port))
                s.sendall(f"{ARGS.callsign}\n".encode())
                buffer = ""
                while True:
                    data = s.recv(4096)
                    if not data:
                        break
                    buffer += data.decode("utf-8", errors="ignore")
                    lines = buffer.split("\n")
                    buffer = lines.pop()
                    for line in lines:
                        if line.strip():
                            process_spot(line.strip())
        except Exception as e:
            print(f"Connection lost ({e}). Reconnecting in 10s...")
            time.sleep(10)


# ===================== PERIODIC ADIF & CTY REFRESH =====================

def refresh_prefix_map():
    """Downloads cty.dat and regenerates dxcc_prefixes.json."""
    global dxcc_prefixes, sorted_prefixes, dxcc_exact, dxcc_excludes
    print("[CTY] Downloading and regenerating prefix map...")
    try:
        script = os.path.join(WORKSPACE, "parse_cty.py")
        result = subprocess.run(["python3", script], capture_output=True, text=True, timeout=60)
        if result.returncode == 0:
            with open(PREFIX_FILE) as f:
                data = json.load(f)
            dxcc_prefixes = data["map"]
            sorted_prefixes = data["prefixes"]
            dxcc_exact = data.get("exact", {})
            dxcc_excludes = data.get("excludes", {})
            dxcc_entities[:] = data.get("dxcc_entities", [])
            region_map.clear()
            region_map.update(data.get("region_map", {}))
            print(f"[CTY] Prefix map updated: {len(dxcc_prefixes)} prefixes, "
                  f"{len(dxcc_exact)} exceptions, {len(dxcc_excludes)} excludes, "
                  f"{len(dxcc_entities)} DXCC entities")
            rebuild_never_worked()
            return True
        else:
            print(f"[CTY] Error running parse_cty.py:\n{result.stderr}")
            return False
    except Exception as e:
        print(f"[CTY] Error updating prefix map: {e}")
        return False


def adif_refresh_loop():
    """Refreshes ADIF every 24h."""
    while True:
        refresh_adif()
        rebuild_never_worked()
        time.sleep(86400)


def cty_refresh_loop():
    """Refreshes cty.dat and prefix map every 24h."""
    while True:
        refresh_prefix_map()
        time.sleep(86400)


# ===================== MAIN =====================

if __name__ == "__main__":
    ARGS = parse_args()
    callsign_display = ARGS.callsign.upper()
    print(f"=== DXCC Monitor ({callsign_display}) ==="
          f" (Filter: year={ARGS.year} modes={ARGS.modes} "
          f"freq={ARGS.freq_min}-{ARGS.freq_max} kHz)")

    if not ARGS.telegram_token:
        print("⚠️  Telegram not configured. Alerts will only appear in console.")
        print("   Use --telegram-token and --telegram-chat-id to enable.")

    # Load prefix map
    load_prefix_map()

    # Download and load initial ADIF
    if ARGS.eqsl_user and ARGS.eqsl_pass:
        print("Downloading logbook...")
        refresh_adif()
    else:
        print("eQSL not configured, loading existing ADIF if available...")
        load_adif()
    rebuild_never_worked()

    # Background ADIF refresh
    t = threading.Thread(target=adif_refresh_loop, daemon=True)
    t.start()

    # Background cty.dat / prefix map refresh
    t2 = threading.Thread(target=cty_refresh_loop, daemon=True)
    t2.start()

    time.sleep(2)

    print("Connecting to DX Cluster...")
    cluster_loop()
